// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPHF6MyNMAT_ouZR-RAqJtgQWhQjMyNA',
    appId: '1:796736896382:web:ff894c780ba2a59ef7072f',
    messagingSenderId: '796736896382',
    projectId: 'preforsa-bbc79',
    authDomain: 'preforsa-bbc79.firebaseapp.com',
    storageBucket: 'preforsa-bbc79.appspot.com',
    measurementId: 'G-9GS64KE55P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7HRxa3UqufK3_BbQzni6isCRXYJBe7Vo',
    appId: '1:796736896382:android:0d006442f298176ef7072f',
    messagingSenderId: '796736896382',
    projectId: 'preforsa-bbc79',
    storageBucket: 'preforsa-bbc79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gLeqP4J-l_wZCU63_ttqn65pJyHOFV4',
    appId: '1:796736896382:ios:948908045e02e617f7072f',
    messagingSenderId: '796736896382',
    projectId: 'preforsa-bbc79',
    storageBucket: 'preforsa-bbc79.appspot.com',
    iosBundleId: 'com.example.preforsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0gLeqP4J-l_wZCU63_ttqn65pJyHOFV4',
    appId: '1:796736896382:ios:948908045e02e617f7072f',
    messagingSenderId: '796736896382',
    projectId: 'preforsa-bbc79',
    storageBucket: 'preforsa-bbc79.appspot.com',
    iosBundleId: 'com.example.preforsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPHF6MyNMAT_ouZR-RAqJtgQWhQjMyNA',
    appId: '1:796736896382:web:03e4a8bf2c5e6ee3f7072f',
    messagingSenderId: '796736896382',
    projectId: 'preforsa-bbc79',
    authDomain: 'preforsa-bbc79.firebaseapp.com',
    storageBucket: 'preforsa-bbc79.appspot.com',
    measurementId: 'G-YX6VZLPWJ4',
  );
}
